version: "3"

services:
  project_cuda116:
      build: .
      privileged: true
      tty: true
      network_mode: "host"
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
          #- /home/hardik/Desktop/Research/FORESEE:/home/FORESEE
        - ./:/home/social-navigation
      environment:
        - DISPLAY=$DISPLAY
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=all
      runtime: nvidia  # not need maybe for display atleast
      deploy:
              resources:
                reservations:
                  devices:
                    - driver: nvidia
                      count: 1
                      capabilities: [gpu]

  jax_cuda:
    build: 
      context: ./
      dockerfile: gpu.Dockerfile
    privileged: true
    tty: true
    network_mode: "host"
    volumes:
       - ./:/home/social_navigation
       - ../wind_disturbance:/home/wind_disturbance
       - /tmp/.X11-unix:/tmp/.X11-unix
       - $HOME/.Xauthority:/home/admin/.Xauthority:rw 
    environment:
      - NVIDIA_DISABLE_REQUIRE=1
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]