version: "3"

services:
  neural-cbf:
    build: .
    privileged: true
    tty: true
    network_mode: "host"
    volumes:
      - /home/hardik/Research/cbfkit-internal/paper_codes/neural_clbf:/home/neural_clbf
        #- /home/hardik/Desktop/Research/Toyota/hsr/:/home/hsr
      # - /home/hardik/Research/hsr/catkin_ws/src/dependencies/CrowdNav:/home/CrowdNav
    environment:
      - NVIDIA_DISABLE_REQUIRE=1
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

