nn_preds_path : "nn_preds.npy"
env_mask_path: "env_mask.npy"
n_xy_bins: 896
n_dof_bins: 10 
goal_tolerance: 0.1


reset: False
visualize: False

abstraction_path: "./abstraction/"
env_name: "env1"
criticality_threshold: 0.7
robot:
  name: "hsrb1"
  model_path: "robot2.xml"
  ndofs: 2
  # llimits:
  #   - -7.5
  #   - -7.5
  #   - -3.14
  # ulimits:
  #   - 7.5
  #   - 7.5
  #   - 7.14

  llimits:
    - -10.0
    - -10.0
    # - -3.14
  ulimits:
    - 10.0
    - 10.0
    # - 3.14